main:
  project_name: census-classification
  experiment_name: development
  components_repository: model_build
  steps: all
  greet_message: "Hello World!"
  train:
    cat_features:
      - age
      - workclass
      - fnlwgt
      - education
      - education-num
      - marital-status
      - occupation
      - relationship
      - race
      - sex
      - capital-gain
      - capital-loss
      - hours-per-week
      - native-country
      - income
data_split:
  input_artifact: "laurent4ml/census-classification/census.csv:latest"
  artifact_root: "census"
  artifact_type: dataset # needs to be dataset
  test_size: 0.20
  random_state: 42
  stratify: "null"
data_check:
  input_artifact_full: "laurent4ml/census-classification/census.csv:latest"
  input_artifact_train: "laurent4ml/census-classification/census_train.csv:latest"
  input_artifact_test: "laurent4ml/census-classification/census_test.csv:latest"
model_check:
  input_artifact: "laurent4ml/census-classification/census_train.csv:latest"
model_training:
  model_name: "Logistic Regression"
  artifact_root: "census"
  model_file: "lr_model.joblib"
model_evaluation:
  artifact_root: "census"
  model_file: "lr_model.joblib"
